name: Azure Costs
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  get-azure-costs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-identity azure-mgmt-costmanagement

    - name: Run cost retrieval script
      run: python get_azure_costs.py
      env:
        DATE_FROM: 2024-04-01  # 環境変数として開始日を設定
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
